//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingObject.CRMServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRMServiceReference.ICRMService")]
    public interface ICRMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMService/ConnectCall", ReplyAction="http://tempuri.org/ICRMService/ConnectCallResponse")]
        void ConnectCall(string uri, string valcookie, string xapp, string listenerName, string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRMService/ConnectCall", ReplyAction="http://tempuri.org/ICRMService/ConnectCallResponse")]
        System.Threading.Tasks.Task ConnectCallAsync(string uri, string valcookie, string xapp, string listenerName, string arg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRMServiceChannel : TestingObject.CRMServiceReference.ICRMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRMServiceClient : System.ServiceModel.ClientBase<TestingObject.CRMServiceReference.ICRMService>, TestingObject.CRMServiceReference.ICRMService {
        
        public CRMServiceClient() {
        }
        
        public CRMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ConnectCall(string uri, string valcookie, string xapp, string listenerName, string arg) {
            base.Channel.ConnectCall(uri, valcookie, xapp, listenerName, arg);
        }
        
        public System.Threading.Tasks.Task ConnectCallAsync(string uri, string valcookie, string xapp, string listenerName, string arg) {
            return base.Channel.ConnectCallAsync(uri, valcookie, xapp, listenerName, arg);
        }
    }
}
